- config/template/config.yaml
- internal/action/pre_run.go
- internal/config/config.go
- internal/run/leveling_act1.go
This pull request adds the possibility to disable skill, stat, reset, and key bindings functionality through config values.
This is done to have flexibility for someone who does not want to these functionalities enabled. E.g. knowing better what and howto allocate, having specific items which, set up the key bindings beforehand etc.
At least personally I've experienced sometimes bot messing up with key bindings and puts TP on F5 and armor on F4. It's easier to set everything myself once and forget about it, however make sure that these will not be reset again accidentally.
> Make skill and stat functionality during leveling optional through config

- internal/action/waypoint.go
`currentWP` is being assigned from `currentWP.LinkedFrom[0]` on line 75 but then again we assign area from LinkedFrom `a = currentWP.LinkedFrom[0]`
If on line 75 `currentWP` becomes a town itself, then `a = currentWP.LinkedFrom[0]` will fail with an error because `currentWP.LinkedFrom` is nil.
This tries to fix this issue.
I did not experience any issues with waypoint discover anymore on my char. Hopefully this will fix it fully.
> Try to fix waypoint discover, try number 2

- config/koolo.yaml.dist
- internal/config/config.go
- internal/manager.go
- internal/server/http_server.go
- internal/server/templates/config.html
- internal/supervisor.go
The idea is to prevent game window overlapping when running multiple instances, it will auto arrange them growing horizontally and then jumping to the next row, from top left to bottom right.
> auto game window arrangement

- internal/run/companion.go
When using leader + followers in e.g. a Baal run, quite often followers exited the game.
After debugging it seems like sometimes `leaderRosterMember.Area` is area.None and thus does not have `.Act()`
> Check Leaders area is not none in companion

- config/template/config.yaml
- internal/action/item_pickup.go
- internal/config/config.go
This PR adds minimal gold pickup threshold as a configurable option.
Basically fixes #138
> Add minimal gold pickup threshold as configurable option #138

- internal/town/A1.go
Sometimes Kashya walks away too far to the right in Act 1. This messes up with finding a portal.
This PR changes that. The first marker to be used is Rogue Bonfire an then a small offset in Y to it. This makes the waiting are much closer to the actual place where TPs are spawn.
As a fallback Kashya is used if Rogue Bonfire has not been found. Can this happen ever?
> Use Rogue Bonfire as the initial object to determine Act 1 TP area

- internal/run/lower_kurast_chests.go
Seems like this change has introduced some issues when pathing and teleporting.
I've been thinking to change the logic of LK chest runs but as a hotfix let's just remove weapon racks completely.
> Remove weapon racks from LK chest run

- internal/run/companion.go
A small PR to improve companion logic a little.
1. Follower should not follow the leader in a town. There is no point, is there? Follower should just wait near TP area.
2. If follower does not have any information about leader attacking a monsters, however there are monsters nearby, follower should not stand idle but attack in this case.
> Add a couple of improvements in companion

- config/template/config.yaml
- internal/config/config.go
- internal/run/ancient_tunnels.go
- internal/run/pit.go
- internal/run/stony_tomb.go
Added focusOnElitePacks & openChests configurations for the following maps:
- Stony Tomb
- Ancient Tunnels
- Pit (added the filter & openChests option to the clearArea call on lvl2)
Also updated the default template accordingly.
> Added focusonelite & openchests option to more maps

- config/template/config.yaml
- internal/action/stash.go
- internal/config/config.go
Hola,
a little something we hardcore players desire, not quite sure if we should put that behind a generic `character: hardcore` setting, or have something more specific like `character.muleToShared`? 
Thanks!
> Add option to not mule into personal, but shared stash (hardcore)

- internal/character/blizzard_sorceress.go
- internal/character/foh.go
Some users (including myself) for unknown reasons - Blizzard build would use CTA but not cast any buffs or would only cast either Energy Shield or Frozen Armor but never both.
I couldn't debug why it's happening, it was running fine for me until I did `git pull` today and the bug also occurred to myself as well.
The changes just ensures that the sorceress would put up existing shields such as Energy Shield and Frozen Armor.
> Fixed a minor bug in blizzard_sorceress.go file.

- internal/action/vendor.go
- internal/town/shop_manager.go
When buying keys, the quantities in inventory and supplied by vendor are now calculated, and the bot does not buy keys if the amount will be greater than 12, this avoids having multiple stacks of keys in inventory accumulating
> Fixed multiple stacks of keys in inventory during runs

- internal/character/lightning_sorceress.go
Add check if we should use static in main attack rotation
* It will occur if more than 50% of mobs within max attack distance +5 are above 60% hp.
> Nova sorc improvements

- internal/action/step/attack.go
- internal/pather/line_of_sight.go
1. **Added boundary checks in `LineOfSight` function:** 
- Ensured that indices `x0` and `y0` are within the valid range of the `d.CollisionGrid` array to prevent out-of-bounds errors.
2. **Adjusted index calculation in `ensureEnemyIsInRange` method:**
- Modified the calculation of `moveTo` to ensure it does not exceed the bounds of the `path` array.
- Ran multiple scenarios to ensure the changes fix the index out of range error without introducing new issues.
- Verified that the bot performs as expected in all tested scenarios.
> Fix index out of range error in LineOfSight and ensureEnemyIsInRange

- internal/bot.go
- Call the b.pauseRequested instead of b.paused directly.
> Fix bot not releasing the mouse on pause due to missing keybinds

- internal/config/config.go
- internal/run/diablo.go
- internal/server/http_server.go
- internal/server/templates/run_settings_components.gohtml
Created a new Diablo/Chaos run.
- Killing Diablo still optional/selectable
- Standard run is fast clear, only running seals and Diablo if selected
- Full clear optional/selectable
The run checks for the 2 different layouts the 3 seal elites can have and travels there accordingly.
With the full clear it follows a set path (layout 1 or 2) and clears around the player, including possible stray monsters.
Around the seals it kills all the surrounding monsters, during full clear it ignores the storm casters.
After activating the seal it moves to a set location, again according the layout 1 or 2, and waits for the seal elite to kill it.
> Updated Diablo Chaos Sanctuary Run

- internal/action/leveling_tools.go
- internal/action/move.go
- internal/character/paladin_leveling.go
- internal/character/sorceress_leveling.go
- internal/character/sorceress_leveling_lightning.go
- internal/run/leveling_act1.go
- internal/run/tristram.go
The leveling scripts now have level requirements for initial skillbinds, apart from tome of town portal.
Changed normal run to:
- Clear Blood Moor until level 3/4
- Do Den of Evil until level 6/7
- Do Tristram Runs until level 14/15
- Do Countess Runs until level 17/18
Also changed how the Cain stones are selected in the Tristram run to prevent getting stuck.
Credits to wheresmycode (https://github.com/wheresmycode/koolo/tree/master)
Few notes for leveling:
- Doesn't seem to work in legacy mode
- I had issues with custom keybinds, best to use standard/legacy keybinds
> Improved leveling

- internal/action/stash.go
* Added separate check to never stash Staff of Kings or the Amulet of the Viper in A2 to ease leveling process
> A2 Leveling stash fix

- internal/server/assets/js/character_settings.js
- internal/server/templates/character_settings.gohtml
* Added search field for disabled runs to find what you are looking for faster
* Added "clear all" button to enabled runs to clear the enabled runs faster
* Added popup mentioning that the leveling character profiles/classes require enabling a leveling run profile, and asks user to either confirm or deny this automated action which will clear all enabled run profiles and auto enable the leveling run profile
> Improvements to setting up Leveling characters

- internal/action/gambling.go
- internal/action/step/attack.go
- internal/action/tp_actions.go
- internal/bot/bot.go
- internal/character/berserk_barb.go
- internal/character/character.go
- internal/context/context.go
- internal/run/travincal.go
This is a fully working travincal berserk barbarian profile.
Its using FindItem on 100% of the corpses. 
Made some exception to barbarian attacks as he is doing melee  and his skill (berserk) has no cooldown.   Normal primaryattack was  making the attacks 2x slower if not more.
It checks if it accidently clicked on durance lvl 1 stairs  then come back to travincal and resume its task. (there could be optimization here it takes up to 15 seconds but works)
had to lock the context to pickup items after killing a monster(only for council) . we must kill all 12 council members before looting/horking . thats why the exception.
- General koolo Fixes
added a  WaitForGameToLoad()  in bot.go  that make sure game is fully loaded  and apply legacygraphics ( if classic mode enabled)  before performing …
> Berserk_barb arrives to v2 (travincal barb for now)

- internal/action/move.go
- internal/action/step/interact_object.go
- internal/game/memory_reader.go
- internal/pather/path_finder.go
- PathFinder will now always return a valid walkable path/position.
- Memory_reader GetData() will only delete duplicate objects that have same position 
- Optimization with interact_object
- Area correction is disabled for open area to prevent looping from areas.  Only enabled for entrances and movetocoords that went on entrance type area.
> PathFinder, GetCachedData, Area Correction fix, interact object

- internal/action/item.go
- internal/action/step/move.go
- internal/run/cows.go
When creating new game it will:
- check if we have WirstLeg and Book in cube already  then transmute portal
- Check if we have Wirstleg in inventory .  If we have book then it will use it .If missing Book then it will purchase one and transmute portal
- If no WirstLeg found then it will check if we have extra Book in inventory and drop it.
this will prevent having multiple Books in inventory
It will also ensure all menus are closed before interacting with cow portal. Should prevent the missing gloves bug.
func IsInLockedInventorySlot(itm data.Item) bool    has been added to Item.go
Removed excess log in step  move.go
> Cow level fixes

- internal/action/town.go
- Stash items that need to remain unid before identifying.
> Stash items before identify

- internal/action/identify.go
Sometimes even after Cain identifies all items, the bot will try to use tome to id the same items again. This is caused by sometimes there being a small delay where the server will say something like "waiting for action to complete".
The current code assumes that identification is completed immediately and as such returns error during this small delay, which causes it to fallback to the default identify with tome.
This pr adds a small delay after interacting with Cain to give it time to complete
> fix cain identify sometimes fails and falls back to using tome

- internal/action/cube_recipes.go
- internal/config/config.go
- internal/server/http_server.go
- internal/server/templates/character_settings.gohtml
- Added option to skip Perfect Amethysts for GrandCharm reroll cube recipe
- Added option to skip Perfect Rubies for GrandCharm reroll cube recipe
> Add option to skip pames and prubys when rerolling charms

- internal/action/step/attack.go
- internal/pather/path_finder.go
Special handling for Arcane Sanctuary for platforms configuration.
Removed excess log for unwalkable monster position in attack.go  isValidMonster func.   This could generate huge log file and make koolo freeze.
> Arcane Sanctuary Grid, remove excess log attack.go

- internal/action/item_pickup.go
- internal/action/step/pickup_item.go
- internal/utils/spiral.go
- Following corrections on ClearAreaAroundPosition wich now doesnt return until everything under giving radius is dead (item in this case).  It shouldnt pickup item anymore when surrounded by monsters.
-  Added a line of sight check inside pickup_item action  in case item dropped on the other side of a wall and we cant pickup from here even if we can hover it.   If ErrNoLOSToItem , it will try to move  further the item because if we simply move at item position it wont work. we still will have no line of sight.
- func moveBeyondItem    is similar to the one in EnsureEnemyIsInrange to overshoot distance,  might consider moving this to utils.
-  new ItemSpiral  that is more precise to items instead of using generic  Spiral  currently used by everything else .  Prevents misclick on UI bar( …
> Item Pickup revision

- internal/action/interaction.go
- internal/action/move.go
- internal/action/waypoint.go
- internal/bot/bot.go
- internal/run/travincal.go
Area correction disabled by default. 
Enabled in travincal run because of high chances to click on stairs to durance lvl 1.  Defer function to disable AreaCorrection after the run.
Correction on bot.go after change to refresh interval (100ms) :
- Prevent spamming hideportraits at start of new game Removed useless RefreshGameData when toggling legacy mode . 
Background loop is refreshing every 100ms so 150ms delay is fine here.
- AreaCorrection is now only verified if enabled
> Area Correction fix (enabled only for travi) + adjustment for HidePortraits with new 100ms refresh

- go.mod
- go.sum
- internal/action/horadric_cube.go
- internal/action/stash.go
- internal/action/tools.go
- internal/action/town.go
- internal/action/waypoint.go
- internal/bot/bot.go
- Bot will detect if Chat openmenu is opened and close it
-  It will clear chat message logs at beginning of run , before stashing -cubing- using waypoint.  Prevent misclick on messages that are on the way.
> Prevent opening chat, clear TZ notification and game message spam

- internal/action/item_pickup.go
- internal/action/step/attack.go
- internal/action/step/move.go
- internal/pather/utils.go
- Fix line of sight issues .  Can run tal rasha tombs and stony tombs now =)
- Will reposition if no damage to target for 3 seconds
- Bot wont teleport in circle anymore with lower end cpu ( it wouldnt detect it reached destination so it would teleport once more , get further from destination making a loop/circle) 
- Moved Overshoot logic to utils package   func (pf *PathFinder) BeyondPosition    
Adding RefreshGameData in step move.go loop fix this at minimal cost considering teleport takes 500ms to 1000ms.   so  extra refresh every 500 to 1000ms
> Fix Teleport in circle and Line of sight improvement

- internal/action/town.go
- internal/bot/bot.go
Has retry mechanism, if still fails after 3 attempt will continue run rather then error out .   InRunReturnTownRoutine()  will be detected by goroutine shortly after.
This fix issue where bot is doing town actions like identifying items, interacting with npc, stashing ( was doing some step dancing) next to portal  in farming area.
> Do town actions only if we made it to town

- internal/action/town.go
When in leader mode, sometimes the character goes back to town for various reasons, and then returns to the group but closes the TP leaving others stranded in town. This makes it that the leader opens a fresh portal when going back from town.
> feature: reopen tp when coming back from town if in leader mode

- internal/action/clear_area.go
- internal/action/interaction.go
- internal/action/step/attack.go
- internal/bot/bot.go
**Seals:**
Prevent bot from teleporting up to 5 time on seals before interacting.
- change to ClearThroughpath :
Increasing step.MoveTo(dest, step.WithDistanceToFinish(7) as option prevent not being to able to finish movement if our destination is center of a large object like Seal in diablo run. is used only for pathing, attack.go or pathfinder will use default DistanceToFinishMoving (4) .
- Change to interaction.go :
Is similar to solution from ClearThroughPath :
if InteractObject with a Seal,  we increase DistanceToFinish so it will consider in range at this distance.  With default 4 it wont be able to reach destination and bounce back on seal since its further then 4 and we dont pass to step.InteractObject until we are in range.
**Koolo crash**
- change to attack.go :
Proper cleanup …
> Fix seals,  prevent issue with koolo closing entirely (crash)

- config/template/config.yaml
- internal/action/interaction.go
- internal/action/item_pickup.go
- internal/action/town.go
- internal/action/vendor.go
- internal/bot/bot.go
- internal/config/config.go
- internal/server/http_server.go
- internal/server/templates/character_settings.gohtml
- internal/town/shop_manager.go
The vendor selected for each act doesn't always have keys or scrolls, so we have to go to another vendor to do so.
This PR adds an additional check for purchasing keys and scrolls to ensure we don't run out. It also adds an option to return to town if we run out of keys. And it will only pick up keys if that option is enabled, or they already had some keys (but less than 12) in their inventory. It will not pickup more to put us over one stack.
Specific scenarios this fixes:
1. Act 2 scrolls will run out and not be re-purchased
2. Act 3 keys will run out and not be re-purchased
> Additional vendor check for keys and scrolls

- config/template/config.yaml
The first time you save a character config, the UI will crash unless you've configured the scheduler.
To reproduce:
1. Add a new character
2. Specify a supervisor and character name
3. Hit save
4. Observer the crash
This PR adds some defaults so that the validation code in `character_settings.js` doesn't barf. Presumably there's a bug in there but this solution seemed reasonably graceful
> Bugfix: UI crashes on first time setup because of validation error in scheduler

- internal/action/horadric_cube.go
- internal/action/stash.go
Added the `ClearMessages()` function to isolate the issue of a possible text entering the stash/cube zone.
Supports additional logs for debugging (if needed).
Sync's state menu and forcefully moves the cursor to a safe location - should prevent the cursor from hovering over any equipped gloves or weapon to accidentally pick it up.
Tested on 40 cow runs (20 runs legacy graphics / 20 runs HD graphics) - no loss of gloves/weapon.
> Potential fix for losing Magefist/gloves/weapon.

- internal/action/clear_area.go
- internal/pather/utils.go
- internal/run/baal.go
- internal/run/diablo.go
Revert:
- Checking for door in LoS calculation is expensive and has no benefit, it increase cpu usage. We should take a different approach for this . We have  func checkMonsterDamage  in attack.go  that handle case where we cant reach enemy so its safe to remove it.
- ClearAreaAroundPosition  no longer require to be looped since itempickup handle monster blocking properly
> Optimization: Revert LoS door check, ClearAreaAroundPosition 

- internal/game/keyboard.go
- internal/game/memory_injector.go
This pr enable Shift Key usage.
ctx.HID.ClickWithModifier(game.LeftButton, screenPos.X, screenPos.Y, game.ShiftKey)
Used for Equipping items or moving back potions from inventory to Belt in correct order if we died.
Original code would always return 0x8000 after doing the comparison, which explains why the modifier behavior wasn't working correctly . **It was reporting the key as pressed regardless of which key was being queried.**
> Enable/Repair game.ShiftKey ( shift + left click )
