hectorgimenez/koolo

internal/action/leveling_tools.go, internal/bot.go, internal/town/A2.go
Lysander does not sell ID scroll, when it runs out the bot will stuck.
Click once at the start of a run to ensure it is not holding anything at hand. Otherwise it get stuck.
=> buy from Drognan

internal/run/companion.go, internal/town/A1.go, internal/town/A2.go, internal/town/A3.go, internal/town/A4.go, internal/town/A5.go, internal/town/town.go
This tries to implement a proof of concept of follower using Companion run.
Some things are taken from https://github.com/hectorgimenez/koolo/pull/76
This should implement the basic of https://github.com/hectorgimenez/koolo/issues/75
I however do not have very high level characters for proper testing. However, we can enhance more if bugs will come
=> Enhance companion run with follower logic

go.mod, go.sum, internal/action/gambling.go, internal/action/item_pickup.go, internal/action/stash.go
This pull request implement the check for maxquantity definitions in the pickit.
=> Implement max quantity check

.gitignore
Some config files and folders interfere and shown as unstaged changes.
This PR ignores everything in config folder except those whitelisted.
=> Ignore all files under config except whitelisted

internal/character/blizzard_sorceress.go
Lower the attack loops before closing distance
=> Blizz sorc improvements

internal/action/action_step_chain.go, internal/bot.go, internal/single_supervisor.go
* Fixed panic caused by trying to access a property of a nil variable.
* Added more checks to avoid panics.
=> Fix panic errors and add more checks to avoid such in the future.

internal/config/config.go
Fixed incorrect name in config
=> Fix rejuvs

internal/action/pre_run.go, internal/action/tools.go
This PR will make use Vigor if it has been bound to a key in town.
=> Use Vigor in town if the skill is bind

internal/character/foh.go
Added usage of holy bolt in between (approximate) cooldowns of fist of the heavens when fighting a demon-type boss (Mephisto, Andariel, Duriel, Diablo, Baal)
=> Foh holybolt

internal/action/buff.go, internal/action/character.go, internal/character/blizzard_sorceress.go, internal/character/character.go, internal/character/hammerdin.go, internal/character/lightning_sorceress.go, internal/character/paladin_leveling.go, internal/character/sorceress_leveling.go, internal/character/sorceress_leveling_lightning.go, internal/character/trapsin.go, internal/server/templates/character_settings.gohtml
Added lightning trapsin character, also updated character buff functions with checks and added a preCTABuff function, so that summons can also have CTA life increase
=> Added lightning trapsin character

internal/manager.go, internal/server/http_server.go
- Added more fail-safes to prevent prevent token auth issues.
- Added more fail-safes to crash detector to prevent token auth issues
=> Added token auth fail-safes

internal/bot.go
- Fix GameFinish event not being sent at all if discord message was disabled.
=> Fix stats display

internal/character/character.go, internal/character/mosaic.go, internal/server/templates/character_settings.gohtml
Correct character profile spelling from "mosiac" to "mosaic".
=> Fix mosaic spelling

internal/game/map_client/client.go, internal/pather/path_finder.go
It seems chaos sanctuary and river of flame aren't the only areas that are merged in some way. This also happens to :
- Blood moor
- Cold plains
- Tamoe Highland
- Outer Cloister
- Black Marsh
=> Path finder fix

go.mod, go.sum, internal/action/character.go, internal/action/check_bindings.go, internal/action/clear_area.go, internal/action/cube_recipes.go, internal/action/heal.go, internal/bot.go, internal/character/blizzard_sorceress.go, internal/character/foh.go, internal/character/hammerdin.go, internal/character/javazon.go, internal/character/lightning_sorceress.go, internal/character/mosaic.go, internal/character/paladin_leveling.go, internal/character/sorceress_leveling.go, internal/character/sorceress_leveling_lightning.go, internal/character/trapsin.go, internal/character/wind_druid.go
- Added a required function to character profiles CheckKeyBindings to ensure the user has all required skills bound to a key.
* If there is one or more missing keybind, it will show a message box with the missing skills
- [EXTRA]: Fixed some spelling mistake in cube_recipes, whoops :)
NOTE: This PR requires https://github.com/hectorgimenez/d2go/pull/27 to be merged to work correctly. If/when it gets merged, I'll update the go.mod file.
=> Verifying Required Skill Keybinds

internal/server/assets/css/debug.css, internal/server/assets/js/debug.js, internal/server/templates/debug.gohtml
- Rewrote entire debug view
- Drastically improved performance and memory usage
- Can now copy the entire data or individual structures or values
- Looks better :)
=> Debugger V2

better_build.bat
- Added better error checking for files/folders permission (for debug reasons)
- Added exit if it fails to delete koolo.exe
=> Improve better build script

internal/action/repair.go
* Restructuring in an attempt to fix problem with constantly trying to repair 100% durability items
=> Restructured conditionals

internal/manager.go
- Added detailed debug logging of positioning
- Reduced distance between windows
- Changed logic of positioning, window position will not be changed if there is no space for it
- Added offset of -10px to align the D2R windows correctly
=> Changed D2R windows positioning

go.mod, go.sum, internal/v2/character/berserk_barb.go, internal/v2/character/blizzard_sorceress.go, internal/v2/character/character.go, internal/v2/character/foh.go, internal/v2/character/hammerdin.go, internal/v2/character/javazon.go, internal/v2/character/lightning_sorceress.go, internal/v2/character/mosaic.go, internal/v2/character/trapsin.go, internal/v2/character/wind_druid.go
- Unified Character Script in logical order of functions for all characters
- Converting character scripts to new actions format
=> Unified Character Script - Adding Characters

internal/v2/action/clear_level.go, internal/v2/run/drifter_cavern.go, internal/v2/run/duriel.go, internal/v2/run/eldritch.go, internal/v2/run/run.go
- Added Drifter Cavern run
- Added Duriel run
- Added Eldritch run
=> Added DrifterCavern, Duriel, Eldritch runs

internal/v2/run/endugu.go, internal/v2/run/lower_kurast.go, internal/v2/run/mausoleum.go, internal/v2/run/nihlathak.go, internal/v2/run/pit.go, internal/v2/run/run.go, internal/v2/run/stony_tomb.go, internal/v2/run/summoner.go, internal/v2/run/threshsocket.go
- Added Endugu
- Added Lower Kurast
- Added Mausoleum
- Added Nihlathak
- Added Pit
- Added Stony Tomb
- Added Summoner
- Added Threshocket
=> Refactored even more runs!

internal/v2/run/mephisto.go, internal/v2/run/run.go, internal/v2/run/tal_rasha_tombs.go, internal/v2/run/tristram.go
- Added Mephisto
- Added Tal Rasha Tombs
- Added Tristram
=> Refactored Mephisto, Tal Tombs, Tristram

internal/v2/action/clear_area.go, internal/v2/action/tools.go, internal/v2/run/diablo.go, internal/v2/run/run.go
Request to check this run because its very large and i'm not 100% sure its correct since I get an import error but the tools.IsMonsterSealElite does work ...
=> Refactor diablo run

config/template/config.yaml, internal/config/config.go, internal/config/runs.go, internal/server/http_server.go, internal/server/templates/run_settings_components.gohtml, internal/v2/run/spider_cavern.go
=> Spider cavern refactor

internal/server/templates/character_settings.gohtml, internal/v2/character/character.go, internal/v2/character/hydraorb_sorceress.go
* Added full hydra/orb sorc script profile
=> Added full build hydra/orb sorc scripts

internal/v2/run/run.go, internal/v2/run/spider_cavern.go
* Fixed erroneous reference for spider cavern run
=> Fix for spider cavern reference

internal/v2/run/lower_kurast_chests.go, internal/v2/run/run.go
* Port (or attempt at) lower kurast chest run
=> Added lower kurast chest run V2

internal/v2/bot/supervisor.go
- Decreased delay from 500ms to 150ms
=> Speed up char select

internal/v2/run/diablo.go
- Added extra error handling in the Diablo run.
- Made sure the skipstormcaster monster filter is applied properly.
- Tweaked the clearpath function to improve clearing Chaos Sanctuary in full clear.
=> Added error handling + tweaked Diablo Run

internal/supervisor.go
Added support for panelmanager for characterselect (new feature in d2go that is also in PR, merge that first!)
=> Added support for panelmanager for characterselect

internal/config/config.go, internal/server/http_server.go, internal/server/templates/character_settings.gohtml, internal/v2/action/item_pickup.go, internal/v2/action/leveling_tools.go, internal/v2/action/tools.go, internal/v2/bot/manager.go, internal/v2/run/baal.go, internal/v2/run/diablo.go
- Add Lobby Games
- RIP Companion mode ... In its current form.
=> Add Lobby Games

internal/config/config.go
Added logging of full path to config load function
=> Update config load

internal/v2/bot/single_supervisor.go
- Using functions from GameReader instead of data from ctx.Data (as it doesn't update for some reason)
- Add a call to s.bot.ctx.GameReader.GetData(true) on new game creation to update map data as well.
=> Update flow & data on new game

internal/v2/bot/single_supervisor.go
- Added a call to refresh game data when in the out of game loop.
=> Refresh Data when not ingame

cmd/koolo/log/logger.go
Change supervisor log names to be Supervisor-log-x-x-x to be able to distinguish them from the main log
=> change supervisor log names

internal/game/manager.go, internal/v2/bot/manager.go
=> More housekeeping

cmd/koolo/main.go, internal/config/config.go, internal/remote/discord/discord_bot.go, internal/remote/discord/discord_command_handlers.go, internal/server/http_server.go, internal/server/templates/config.gohtml
Initial implementation of remote control
=> Remote control via discord

internal/action/item_pickup.go
Reduce monster check radius for item pickup
=> Adjust item pickup

internal/action/identify.go, internal/action/town.go, internal/town/A1.go, internal/town/A2.go, internal/town/A3.go, internal/town/A4.go, internal/town/A5.go, internal/town/town.go
- Added Cain IDs to each town's NPC list
- Added function to check if there are items that should be stashed unidentified
- Added function to use Cain to identify the items
=> Cain identify - initial implementation

go.mod, go.sum, internal/action/stash.go
- Fix default return on ShouldStashIt
- Update d2go to latest
=> Fix ShouldStashIt

internal/bot/manager.go, internal/remote/discord/discord_command_handlers.go, internal/server/assets/css/dashboard.css, internal/server/assets/js/dashboard.js, internal/server/http_server.go, internal/server/templates/index.gohtml
- Moved Crash Detector function into buildSupervisor
- 3 new arguments added to SupervisorManager.Start (1 required 2 optional)
- Added new button "Attach" to index and popup window with process list.
- Added a few more windows functions to http server (probably need to separate them in their own file later on)
=> Attach to existing process

cmd/koolo/main.go, internal/bot/scheduler.go, internal/bot/supervisor.go, internal/config/config.go, internal/server/assets/css/custom.css, internal/server/assets/js/character_settings.js, internal/server/http_server.go, internal/server/template_parameters.go, internal/server/templates/character_settings.gohtml
- Added a scheduler to Koolo.
- Supports multiple times/day
=> Scheduler Implementation

internal/character/mosaic.go
- Added checks for the charges we have to ensure we always have the right number of charges
=> Feed the Mosiac script some steroids

internal/action/belt_manage.go, internal/action/town.go
- Added a check to identify and consume any potions in our belt that don't fit our configuration.
=> Consume misplaced belt potions

internal/bot/manager.go, internal/utils/winproc/user32.go
- Change D2R Game window title to format "D2R - [PID] - supervisor - region"
=> Change Game Window Title

internal/action/step/attack.go
Initial Telestomp implementation
=> Add Telestomp

internal/bot/single_supervisor.go
- Check required character profile key binds on first run.
=> Check required key binds

internal/config/config.go, internal/run/diablo.go, internal/server/http_server.go, internal/server/templates/run_settings_components.gohtml
It now (mostly) waits for the seal elite but sometimes it already kills it before the end of the check.
Also condensed functions, went from 580 to 380 lines, and added option to skip stormcasters.
=> Fixed diablo run

internal/action/horadric_cube.go, internal/action/stash.go, internal/action/vendor.go
- OpenStash
- CloseStash
- TakeItemsFromStash
=> Add Stash actions

internal/character/berserk_barb.go, internal/config/config.go, internal/run/travincal.go, internal/server/http_server.go, internal/server/templates/character_settings.gohtml
a configurable option to swap items to  goldfind items before using skill FindItem on corpses.  
Swap back if attacking/begining of run.
very basic for now
=> Swap Items before Hork ( Barbarian)

go.mod, go.sum, internal/action/buff.go
- Fix buffing if you don't have CTA
- Update d2go to latest corpse offsets
=> Buff and Corpse fixes

internal/action/move.go, internal/remote/discord/discord_event_handler.go
Prevent movement if there are any open menus. Close them first.
=> Close open menus on movement

internal/run/countess.go
using countess chest position from cached data ( fetch 1.13c) to make sure we detect properly.
=> Countess run fix

internal/bot/bot.go
- Add logging for back to town reason
=> chore: Log the reason why we're going to town

internal/action/buff.go
minor optimization potentially reducing number of distance calcs
=> minor buff check optimization

internal/action/step/attack.go
- Fix the ensureEnemyIsInRange implementation for mele characters.
=> Fix mele range chars

internal/action/horadric_cube.go
- Use the calculated position instead of a hard-coded position.
=> fix taking items from cube

internal/bot/manager.go, internal/config/config.go, internal/context/context.go, internal/game/memory_reader.go, internal/server/assets/css/dashboard.css, internal/server/assets/js/dashboard.js, internal/server/http_server.go, internal/server/templates/character_settings.gohtml, internal/server/templates/config.gohtml, internal/server/templates/index.gohtml
- Added an option to Koolo settings to set centralized pickit path
- Added per-character option to use the centralized pickit path
- Added a reload config button to main dashboard.
=> Implement centralized pickit option

config/template/config.yaml, go.mod, go.sum, internal/action/tools.go, internal/bot/bot.go, internal/config/config.go, internal/server/http_server.go, internal/server/templates/character_settings.gohtml
New Configurable Option in Character settings to hide mercenary/ other players portraits. Prevent misclick and opening merc inventory. Will happen at same time as togglelegacy.
=> Option Hide Portraits(prevent missing merc items)

go.mod, go.sum, internal/bot/bot.go
- Update D2GO lib with the fix for stats
- Reduce memory reading to once every 100ms (up from 10ms) to reduce the CPU usage.
=> Fix stats and small CPU improvement

internal/action/gambling.go
-Gambling will stop if game time limit exceed
-Now pausable
-Will close gamble menu and reopen it after 10 attempt to prevent infinite loop bug when it cant find item.
=> Repair 3 bug with gambling

internal/action/cube_recipes.go, internal/config/config.go, internal/run/arachnid_lair.go, internal/server/http_server.go, internal/server/templates/run_settings_components.gohtml
- Added Elite only filter for Arachnid Lair.
- Added Open Chest configurable option for Arachnid Lair
- Fixed Safety Armor and Shield recipes
=> Filter for Arachnid Lair and Recipe fix

internal/server/templates/run_settings_components.gohtml
Fixed incorrect checkbox name.
=> Fix Meph Config Update run_settings_components.gohtml

internal/config/config.go, internal/run/terror_zone.go, internal/server/http_server.go, internal/server/templates/run_settings_components.gohtml
Adds option to open chests during terror zone area clearing
=> Terror zone open chests option

internal/character/character.go, internal/character/fireball_sorc.go, internal/server/templates/character_settings.gohtml
=> Fireball sorc

config/template/config.yaml, internal/action/interaction.go, internal/action/item_pickup.go, internal/action/vendor.go, internal/bot/bot.go, internal/config/config.go, internal/server/http_server.go, internal/server/templates/character_settings.gohtml, internal/town/shop_manager.go
Reverts hectorgimenez/koolo#628
=> Revert "Additional vendor check for keys and scrolls"

internal/action/cube_recipes.go
Check remaining items when looping recipes by refreshing collection.
=> Fix for cubing recipes with misssing items

internal/action/stash.go, internal/action/step/pickup_item.go, internal/bot/bot.go, internal/context/context.go, internal/game/area.go, internal/run/spider_cavern.go, internal/server/templates/drops.gohtml
First implementation of a new DROPs page.
- Redesigned drop page completely
- Added drop location :)
- Added search
- Other small bugfixes, improvements and additions
=> New drops UI

go.mod, go.sum, internal/action/repair.go, internal/bot/bot.go, internal/run/terror_zone.go, internal/server/http_server.go, internal/server/templates/drops.gohtml
- Updated d2go to latest
- Fixes for broken stats display
- Identify Active weapon slot
- Item Level Requirement
- Added Actual item names (identified names)
- Attempt to fix TZs
- Fix for back to town repair loop
- Drop UI goodies
=> Fixes and stuff

go.mod, go.sum, internal/game/data.go
- Update d2go to latest with CPU improvements.
- Decreased hard-coded value for wait-time between TPs
=> More CPU Improvements and Faster TPs

internal/character/blizzard_sorceress.go, internal/character/wind_druid.go
Title says it all, I had successful runs with most areas such as Pit, CS, Baal, Andariel, Mephisto, Travincal - no errors/issues.
If any errors/bugs occur please reach out to me on discord at **Void**.
=> Update Tornado Druid (wing_druig.go) to work with latest code base of Koolo

internal/action/horadric_cube.go, internal/action/stash.go
Reverts hectorgimenez/koolo#728
=> Revert "Potential fix for losing Magefist/gloves/weapon."

cmd/koolo/log/logger.go, cmd/koolo/main.go, internal/bot/single_supervisor.go, internal/config/config.go, internal/remote/discord/discord_event_handler.go, internal/server/http_server.go, internal/server/templates/config.gohtml
- Add an option to enable and disable error messages in discord (not screenshot messages)
- Added more logging handling
=> Discord message settings ++
